spring:
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: meals
      schema-action: create_if_not_exists
      entity-base-package: com.meals.thirtyminutemeals.model
