service:
  base:
    url: "http://localhost:8080"

spring:
  data:
    cassandra:
      port: 9042
      contact-points: cassandra
      keyspace-name: meals
      schema-action: create_if_not_exists
      entity-base-package: com.meals.thirtyminutemeals.model
